/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DtpcPlayButton {
        "iconStyle": string;
    }
    interface DtpcPlayer {
        /**
          * Audio source URL.
         */
        "src": string;
    }
    interface IconPause {
        "alignmentBaseline": any;
        "baselineShift": any;
        "clipPath": any;
        "clipRule": any;
        "color": any;
        "colorInterpolation": any;
        "colorInterpolationFilters": any;
        "colorRendering": any;
        "cursor": any;
        "cx": any;
        "cy": any;
        "d": any;
        "direction": any;
        "display": any;
        "dominantBaseline": any;
        "fill": any;
        "fillOpacity": any;
        "fillRule": any;
        "filter": any;
        "floodColor": any;
        "floodOpacity": any;
        "font": any;
        "fontFamily": any;
        "fontKerning": any;
        "fontSize": any;
        "fontSizeAdjust": any;
        "fontStretch": any;
        "fontStyle": any;
        "fontVariant": any;
        "fontWeight": any;
        "height": any;
        "imageRendering": any;
        "isolation": any;
        "letterSpacing": any;
        "lightingColor": any;
        "marker": any;
        "markerEnd": any;
        "markerMid": any;
        "markerStart": any;
        "mask": any;
        "maskClip": any;
        "maskComposite": any;
        "maskImage": any;
        "maskMode": any;
        "maskOrigin": any;
        "maskPosition": any;
        "maskRepeat": any;
        "maskSize": any;
        "maskType": any;
        "opacity": any;
        "overflow": any;
        "pointerEvents": any;
        "r": any;
        "rx": any;
        "ry": any;
        "shapeRendering": any;
        "stopColor": any;
        "stopOpacity": any;
        "stroke": any;
        "strokeDasharray": any;
        "strokeDashoffset": any;
        "strokeLinecap": any;
        "strokeLinejoin": any;
        "strokeMiterlimit": any;
        "strokeOpacity": any;
        "strokeWidth": any;
        "textAnchor": any;
        "textDecoration": any;
        "textOrientation": any;
        "textRendering": any;
        "transform": any;
        "transformBox": any;
        "transformOrigin": any;
        "unicodeBidi": any;
        "visibility": any;
        "width": any;
        "wordSpacing": any;
        "writingMode": any;
        "x": any;
        "y": any;
    }
    interface IconPlay {
        "alignmentBaseline": any;
        "baselineShift": any;
        "clipPath": any;
        "clipRule": any;
        "color": any;
        "colorInterpolation": any;
        "colorInterpolationFilters": any;
        "colorRendering": any;
        "cursor": any;
        "cx": any;
        "cy": any;
        "d": any;
        "direction": any;
        "display": any;
        "dominantBaseline": any;
        "fill": any;
        "fillOpacity": any;
        "fillRule": any;
        "filter": any;
        "floodColor": any;
        "floodOpacity": any;
        "font": any;
        "fontFamily": any;
        "fontKerning": any;
        "fontSize": any;
        "fontSizeAdjust": any;
        "fontStretch": any;
        "fontStyle": any;
        "fontVariant": any;
        "fontWeight": any;
        "height": any;
        "imageRendering": any;
        "isolation": any;
        "letterSpacing": any;
        "lightingColor": any;
        "marker": any;
        "markerEnd": any;
        "markerMid": any;
        "markerStart": any;
        "mask": any;
        "maskClip": any;
        "maskComposite": any;
        "maskImage": any;
        "maskMode": any;
        "maskOrigin": any;
        "maskPosition": any;
        "maskRepeat": any;
        "maskSize": any;
        "maskType": any;
        "opacity": any;
        "overflow": any;
        "pointerEvents": any;
        "r": any;
        "rx": any;
        "ry": any;
        "shapeRendering": any;
        "stopColor": any;
        "stopOpacity": any;
        "stroke": any;
        "strokeDasharray": any;
        "strokeDashoffset": any;
        "strokeLinecap": any;
        "strokeLinejoin": any;
        "strokeMiterlimit": any;
        "strokeOpacity": any;
        "strokeWidth": any;
        "textAnchor": any;
        "textDecoration": any;
        "textOrientation": any;
        "textRendering": any;
        "transform": any;
        "transformBox": any;
        "transformOrigin": any;
        "unicodeBidi": any;
        "visibility": any;
        "width": any;
        "wordSpacing": any;
        "writingMode": any;
        "x": any;
        "y": any;
    }
}
declare global {
    interface HTMLDtpcPlayButtonElement extends Components.DtpcPlayButton, HTMLStencilElement {
    }
    var HTMLDtpcPlayButtonElement: {
        prototype: HTMLDtpcPlayButtonElement;
        new (): HTMLDtpcPlayButtonElement;
    };
    interface HTMLDtpcPlayerElement extends Components.DtpcPlayer, HTMLStencilElement {
    }
    var HTMLDtpcPlayerElement: {
        prototype: HTMLDtpcPlayerElement;
        new (): HTMLDtpcPlayerElement;
    };
    interface HTMLIconPauseElement extends Components.IconPause, HTMLStencilElement {
    }
    var HTMLIconPauseElement: {
        prototype: HTMLIconPauseElement;
        new (): HTMLIconPauseElement;
    };
    interface HTMLIconPlayElement extends Components.IconPlay, HTMLStencilElement {
    }
    var HTMLIconPlayElement: {
        prototype: HTMLIconPlayElement;
        new (): HTMLIconPlayElement;
    };
    interface HTMLElementTagNameMap {
        "dtpc-play-button": HTMLDtpcPlayButtonElement;
        "dtpc-player": HTMLDtpcPlayerElement;
        "icon-pause": HTMLIconPauseElement;
        "icon-play": HTMLIconPlayElement;
    }
}
declare namespace LocalJSX {
    interface DtpcPlayButton {
        "iconStyle"?: string;
    }
    interface DtpcPlayer {
        /**
          * Audio source URL.
         */
        "src"?: string;
    }
    interface IconPause {
        "alignmentBaseline"?: any;
        "baselineShift"?: any;
        "clipPath"?: any;
        "clipRule"?: any;
        "color"?: any;
        "colorInterpolation"?: any;
        "colorInterpolationFilters"?: any;
        "colorRendering"?: any;
        "cursor"?: any;
        "cx"?: any;
        "cy"?: any;
        "d"?: any;
        "direction"?: any;
        "display"?: any;
        "dominantBaseline"?: any;
        "fill"?: any;
        "fillOpacity"?: any;
        "fillRule"?: any;
        "filter"?: any;
        "floodColor"?: any;
        "floodOpacity"?: any;
        "font"?: any;
        "fontFamily"?: any;
        "fontKerning"?: any;
        "fontSize"?: any;
        "fontSizeAdjust"?: any;
        "fontStretch"?: any;
        "fontStyle"?: any;
        "fontVariant"?: any;
        "fontWeight"?: any;
        "height"?: any;
        "imageRendering"?: any;
        "isolation"?: any;
        "letterSpacing"?: any;
        "lightingColor"?: any;
        "marker"?: any;
        "markerEnd"?: any;
        "markerMid"?: any;
        "markerStart"?: any;
        "mask"?: any;
        "maskClip"?: any;
        "maskComposite"?: any;
        "maskImage"?: any;
        "maskMode"?: any;
        "maskOrigin"?: any;
        "maskPosition"?: any;
        "maskRepeat"?: any;
        "maskSize"?: any;
        "maskType"?: any;
        "opacity"?: any;
        "overflow"?: any;
        "pointerEvents"?: any;
        "r"?: any;
        "rx"?: any;
        "ry"?: any;
        "shapeRendering"?: any;
        "stopColor"?: any;
        "stopOpacity"?: any;
        "stroke"?: any;
        "strokeDasharray"?: any;
        "strokeDashoffset"?: any;
        "strokeLinecap"?: any;
        "strokeLinejoin"?: any;
        "strokeMiterlimit"?: any;
        "strokeOpacity"?: any;
        "strokeWidth"?: any;
        "textAnchor"?: any;
        "textDecoration"?: any;
        "textOrientation"?: any;
        "textRendering"?: any;
        "transform"?: any;
        "transformBox"?: any;
        "transformOrigin"?: any;
        "unicodeBidi"?: any;
        "visibility"?: any;
        "width"?: any;
        "wordSpacing"?: any;
        "writingMode"?: any;
        "x"?: any;
        "y"?: any;
    }
    interface IconPlay {
        "alignmentBaseline"?: any;
        "baselineShift"?: any;
        "clipPath"?: any;
        "clipRule"?: any;
        "color"?: any;
        "colorInterpolation"?: any;
        "colorInterpolationFilters"?: any;
        "colorRendering"?: any;
        "cursor"?: any;
        "cx"?: any;
        "cy"?: any;
        "d"?: any;
        "direction"?: any;
        "display"?: any;
        "dominantBaseline"?: any;
        "fill"?: any;
        "fillOpacity"?: any;
        "fillRule"?: any;
        "filter"?: any;
        "floodColor"?: any;
        "floodOpacity"?: any;
        "font"?: any;
        "fontFamily"?: any;
        "fontKerning"?: any;
        "fontSize"?: any;
        "fontSizeAdjust"?: any;
        "fontStretch"?: any;
        "fontStyle"?: any;
        "fontVariant"?: any;
        "fontWeight"?: any;
        "height"?: any;
        "imageRendering"?: any;
        "isolation"?: any;
        "letterSpacing"?: any;
        "lightingColor"?: any;
        "marker"?: any;
        "markerEnd"?: any;
        "markerMid"?: any;
        "markerStart"?: any;
        "mask"?: any;
        "maskClip"?: any;
        "maskComposite"?: any;
        "maskImage"?: any;
        "maskMode"?: any;
        "maskOrigin"?: any;
        "maskPosition"?: any;
        "maskRepeat"?: any;
        "maskSize"?: any;
        "maskType"?: any;
        "opacity"?: any;
        "overflow"?: any;
        "pointerEvents"?: any;
        "r"?: any;
        "rx"?: any;
        "ry"?: any;
        "shapeRendering"?: any;
        "stopColor"?: any;
        "stopOpacity"?: any;
        "stroke"?: any;
        "strokeDasharray"?: any;
        "strokeDashoffset"?: any;
        "strokeLinecap"?: any;
        "strokeLinejoin"?: any;
        "strokeMiterlimit"?: any;
        "strokeOpacity"?: any;
        "strokeWidth"?: any;
        "textAnchor"?: any;
        "textDecoration"?: any;
        "textOrientation"?: any;
        "textRendering"?: any;
        "transform"?: any;
        "transformBox"?: any;
        "transformOrigin"?: any;
        "unicodeBidi"?: any;
        "visibility"?: any;
        "width"?: any;
        "wordSpacing"?: any;
        "writingMode"?: any;
        "x"?: any;
        "y"?: any;
    }
    interface IntrinsicElements {
        "dtpc-play-button": DtpcPlayButton;
        "dtpc-player": DtpcPlayer;
        "icon-pause": IconPause;
        "icon-play": IconPlay;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dtpc-play-button": LocalJSX.DtpcPlayButton & JSXBase.HTMLAttributes<HTMLDtpcPlayButtonElement>;
            "dtpc-player": LocalJSX.DtpcPlayer & JSXBase.HTMLAttributes<HTMLDtpcPlayerElement>;
            "icon-pause": LocalJSX.IconPause & JSXBase.HTMLAttributes<HTMLIconPauseElement>;
            "icon-play": LocalJSX.IconPlay & JSXBase.HTMLAttributes<HTMLIconPlayElement>;
        }
    }
}
