/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DtpcButton {
    }
    interface DtpcMuteButton {
    }
    interface DtpcPlayButton {
    }
    interface DtpcPlayer {
        "duration": number;
        /**
          * Audio source URL.
         */
        "src": string;
    }
    interface DtpcProgressBar {
        "duration": number;
    }
    interface DtpcSlider {
        "defaultValue": number;
        "disabled": boolean;
        "max": number;
        "min": number;
        "orient": 'vertical' | 'horizontal';
        "step": number;
        "value": number;
    }
    interface DtpcTimeCurrent {
    }
    interface DtpcTimeDisplay {
        "duration": number;
    }
    interface DtpcTimeDuration {
        "duration": number;
    }
    interface DtpcVolumeSlider {
        "orient": 'vertical' | 'horizontal';
        "volume": number;
    }
    interface IconPause {
        "alignmentBaseline": any;
        "baselineShift": any;
        "clipPath": any;
        "clipRule": any;
        "color": any;
        "colorInterpolation": any;
        "colorInterpolationFilters": any;
        "colorRendering": any;
        "cursor": any;
        "cx": any;
        "cy": any;
        "d": any;
        "direction": any;
        "display": any;
        "dominantBaseline": any;
        "fill": any;
        "fillOpacity": any;
        "fillRule": any;
        "filter": any;
        "floodColor": any;
        "floodOpacity": any;
        "font": any;
        "fontFamily": any;
        "fontKerning": any;
        "fontSize": any;
        "fontSizeAdjust": any;
        "fontStretch": any;
        "fontStyle": any;
        "fontVariant": any;
        "fontWeight": any;
        "height": any;
        "imageRendering": any;
        "isolation": any;
        "letterSpacing": any;
        "lightingColor": any;
        "marker": any;
        "markerEnd": any;
        "markerMid": any;
        "markerStart": any;
        "mask": any;
        "maskClip": any;
        "maskComposite": any;
        "maskImage": any;
        "maskMode": any;
        "maskOrigin": any;
        "maskPosition": any;
        "maskRepeat": any;
        "maskSize": any;
        "maskType": any;
        "opacity": any;
        "overflow": any;
        "pointerEvents": any;
        "r": any;
        "rx": any;
        "ry": any;
        "shapeRendering": any;
        "stopColor": any;
        "stopOpacity": any;
        "stroke": any;
        "strokeDasharray": any;
        "strokeDashoffset": any;
        "strokeLinecap": any;
        "strokeLinejoin": any;
        "strokeMiterlimit": any;
        "strokeOpacity": any;
        "strokeWidth": any;
        "textAnchor": any;
        "textDecoration": any;
        "textOrientation": any;
        "textRendering": any;
        "transform": any;
        "transformBox": any;
        "transformOrigin": any;
        "unicodeBidi": any;
        "visibility": any;
        "width": any;
        "wordSpacing": any;
        "writingMode": any;
        "x": any;
        "y": any;
    }
    interface IconPlay {
        "alignmentBaseline": any;
        "baselineShift": any;
        "clipPath": any;
        "clipRule": any;
        "color": any;
        "colorInterpolation": any;
        "colorInterpolationFilters": any;
        "colorRendering": any;
        "cursor": any;
        "cx": any;
        "cy": any;
        "d": any;
        "direction": any;
        "display": any;
        "dominantBaseline": any;
        "fill": any;
        "fillOpacity": any;
        "fillRule": any;
        "filter": any;
        "floodColor": any;
        "floodOpacity": any;
        "font": any;
        "fontFamily": any;
        "fontKerning": any;
        "fontSize": any;
        "fontSizeAdjust": any;
        "fontStretch": any;
        "fontStyle": any;
        "fontVariant": any;
        "fontWeight": any;
        "height": any;
        "imageRendering": any;
        "isolation": any;
        "letterSpacing": any;
        "lightingColor": any;
        "marker": any;
        "markerEnd": any;
        "markerMid": any;
        "markerStart": any;
        "mask": any;
        "maskClip": any;
        "maskComposite": any;
        "maskImage": any;
        "maskMode": any;
        "maskOrigin": any;
        "maskPosition": any;
        "maskRepeat": any;
        "maskSize": any;
        "maskType": any;
        "opacity": any;
        "overflow": any;
        "pointerEvents": any;
        "r": any;
        "rx": any;
        "ry": any;
        "shapeRendering": any;
        "stopColor": any;
        "stopOpacity": any;
        "stroke": any;
        "strokeDasharray": any;
        "strokeDashoffset": any;
        "strokeLinecap": any;
        "strokeLinejoin": any;
        "strokeMiterlimit": any;
        "strokeOpacity": any;
        "strokeWidth": any;
        "textAnchor": any;
        "textDecoration": any;
        "textOrientation": any;
        "textRendering": any;
        "transform": any;
        "transformBox": any;
        "transformOrigin": any;
        "unicodeBidi": any;
        "visibility": any;
        "width": any;
        "wordSpacing": any;
        "writingMode": any;
        "x": any;
        "y": any;
    }
    interface IconVolume {
        "alignmentBaseline": any;
        "baselineShift": any;
        "clipPath": any;
        "clipRule": any;
        "color": any;
        "colorInterpolation": any;
        "colorInterpolationFilters": any;
        "colorRendering": any;
        "cursor": any;
        "cx": any;
        "cy": any;
        "d": any;
        "direction": any;
        "display": any;
        "dominantBaseline": any;
        "fill": any;
        "fillOpacity": any;
        "fillRule": any;
        "filter": any;
        "floodColor": any;
        "floodOpacity": any;
        "font": any;
        "fontFamily": any;
        "fontKerning": any;
        "fontSize": any;
        "fontSizeAdjust": any;
        "fontStretch": any;
        "fontStyle": any;
        "fontVariant": any;
        "fontWeight": any;
        "height": any;
        "imageRendering": any;
        "isolation": any;
        "letterSpacing": any;
        "lightingColor": any;
        "marker": any;
        "markerEnd": any;
        "markerMid": any;
        "markerStart": any;
        "mask": any;
        "maskClip": any;
        "maskComposite": any;
        "maskImage": any;
        "maskMode": any;
        "maskOrigin": any;
        "maskPosition": any;
        "maskRepeat": any;
        "maskSize": any;
        "maskType": any;
        "muted": boolean;
        "opacity": any;
        "overflow": any;
        "pointerEvents": any;
        "r": any;
        "rx": any;
        "ry": any;
        "shapeRendering": any;
        "stopColor": any;
        "stopOpacity": any;
        "stroke": any;
        "strokeDasharray": any;
        "strokeDashoffset": any;
        "strokeLinecap": any;
        "strokeLinejoin": any;
        "strokeMiterlimit": any;
        "strokeOpacity": any;
        "strokeWidth": any;
        "textAnchor": any;
        "textDecoration": any;
        "textOrientation": any;
        "textRendering": any;
        "transform": any;
        "transformBox": any;
        "transformOrigin": any;
        "unicodeBidi": any;
        "visibility": any;
        "volume": number;
        "width": any;
        "wordSpacing": any;
        "writingMode": any;
        "x": any;
        "y": any;
    }
}
export interface DtpcMuteButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDtpcMuteButtonElement;
}
export interface DtpcPlayButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDtpcPlayButtonElement;
}
export interface DtpcProgressBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDtpcProgressBarElement;
}
export interface DtpcSliderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDtpcSliderElement;
}
export interface DtpcTimeCurrentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDtpcTimeCurrentElement;
}
export interface DtpcTimeDurationCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDtpcTimeDurationElement;
}
export interface DtpcVolumeSliderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDtpcVolumeSliderElement;
}
declare global {
    interface HTMLDtpcButtonElement extends Components.DtpcButton, HTMLStencilElement {
    }
    var HTMLDtpcButtonElement: {
        prototype: HTMLDtpcButtonElement;
        new (): HTMLDtpcButtonElement;
    };
    interface HTMLDtpcMuteButtonElementEventMap {
        "dtpc-control-init": any;
    }
    interface HTMLDtpcMuteButtonElement extends Components.DtpcMuteButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDtpcMuteButtonElementEventMap>(type: K, listener: (this: HTMLDtpcMuteButtonElement, ev: DtpcMuteButtonCustomEvent<HTMLDtpcMuteButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDtpcMuteButtonElementEventMap>(type: K, listener: (this: HTMLDtpcMuteButtonElement, ev: DtpcMuteButtonCustomEvent<HTMLDtpcMuteButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDtpcMuteButtonElement: {
        prototype: HTMLDtpcMuteButtonElement;
        new (): HTMLDtpcMuteButtonElement;
    };
    interface HTMLDtpcPlayButtonElementEventMap {
        "dtpc-control-init": any;
        "audio-toggle-paused": any;
    }
    interface HTMLDtpcPlayButtonElement extends Components.DtpcPlayButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDtpcPlayButtonElementEventMap>(type: K, listener: (this: HTMLDtpcPlayButtonElement, ev: DtpcPlayButtonCustomEvent<HTMLDtpcPlayButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDtpcPlayButtonElementEventMap>(type: K, listener: (this: HTMLDtpcPlayButtonElement, ev: DtpcPlayButtonCustomEvent<HTMLDtpcPlayButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDtpcPlayButtonElement: {
        prototype: HTMLDtpcPlayButtonElement;
        new (): HTMLDtpcPlayButtonElement;
    };
    interface HTMLDtpcPlayerElement extends Components.DtpcPlayer, HTMLStencilElement {
    }
    var HTMLDtpcPlayerElement: {
        prototype: HTMLDtpcPlayerElement;
        new (): HTMLDtpcPlayerElement;
    };
    interface HTMLDtpcProgressBarElementEventMap {
        "dtpc-control-init": any;
    }
    interface HTMLDtpcProgressBarElement extends Components.DtpcProgressBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDtpcProgressBarElementEventMap>(type: K, listener: (this: HTMLDtpcProgressBarElement, ev: DtpcProgressBarCustomEvent<HTMLDtpcProgressBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDtpcProgressBarElementEventMap>(type: K, listener: (this: HTMLDtpcProgressBarElement, ev: DtpcProgressBarCustomEvent<HTMLDtpcProgressBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDtpcProgressBarElement: {
        prototype: HTMLDtpcProgressBarElement;
        new (): HTMLDtpcProgressBarElement;
    };
    interface HTMLDtpcSliderElementEventMap {
        "slider-change": number;
        "slider-input": number;
    }
    interface HTMLDtpcSliderElement extends Components.DtpcSlider, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDtpcSliderElementEventMap>(type: K, listener: (this: HTMLDtpcSliderElement, ev: DtpcSliderCustomEvent<HTMLDtpcSliderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDtpcSliderElementEventMap>(type: K, listener: (this: HTMLDtpcSliderElement, ev: DtpcSliderCustomEvent<HTMLDtpcSliderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDtpcSliderElement: {
        prototype: HTMLDtpcSliderElement;
        new (): HTMLDtpcSliderElement;
    };
    interface HTMLDtpcTimeCurrentElementEventMap {
        "dtpc-control-init": any;
    }
    interface HTMLDtpcTimeCurrentElement extends Components.DtpcTimeCurrent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDtpcTimeCurrentElementEventMap>(type: K, listener: (this: HTMLDtpcTimeCurrentElement, ev: DtpcTimeCurrentCustomEvent<HTMLDtpcTimeCurrentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDtpcTimeCurrentElementEventMap>(type: K, listener: (this: HTMLDtpcTimeCurrentElement, ev: DtpcTimeCurrentCustomEvent<HTMLDtpcTimeCurrentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDtpcTimeCurrentElement: {
        prototype: HTMLDtpcTimeCurrentElement;
        new (): HTMLDtpcTimeCurrentElement;
    };
    interface HTMLDtpcTimeDisplayElement extends Components.DtpcTimeDisplay, HTMLStencilElement {
    }
    var HTMLDtpcTimeDisplayElement: {
        prototype: HTMLDtpcTimeDisplayElement;
        new (): HTMLDtpcTimeDisplayElement;
    };
    interface HTMLDtpcTimeDurationElementEventMap {
        "dtpc-control-init": any;
    }
    interface HTMLDtpcTimeDurationElement extends Components.DtpcTimeDuration, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDtpcTimeDurationElementEventMap>(type: K, listener: (this: HTMLDtpcTimeDurationElement, ev: DtpcTimeDurationCustomEvent<HTMLDtpcTimeDurationElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDtpcTimeDurationElementEventMap>(type: K, listener: (this: HTMLDtpcTimeDurationElement, ev: DtpcTimeDurationCustomEvent<HTMLDtpcTimeDurationElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDtpcTimeDurationElement: {
        prototype: HTMLDtpcTimeDurationElement;
        new (): HTMLDtpcTimeDurationElement;
    };
    interface HTMLDtpcVolumeSliderElementEventMap {
        "dtpc-control-init": any;
    }
    interface HTMLDtpcVolumeSliderElement extends Components.DtpcVolumeSlider, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDtpcVolumeSliderElementEventMap>(type: K, listener: (this: HTMLDtpcVolumeSliderElement, ev: DtpcVolumeSliderCustomEvent<HTMLDtpcVolumeSliderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDtpcVolumeSliderElementEventMap>(type: K, listener: (this: HTMLDtpcVolumeSliderElement, ev: DtpcVolumeSliderCustomEvent<HTMLDtpcVolumeSliderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDtpcVolumeSliderElement: {
        prototype: HTMLDtpcVolumeSliderElement;
        new (): HTMLDtpcVolumeSliderElement;
    };
    interface HTMLIconPauseElement extends Components.IconPause, HTMLStencilElement {
    }
    var HTMLIconPauseElement: {
        prototype: HTMLIconPauseElement;
        new (): HTMLIconPauseElement;
    };
    interface HTMLIconPlayElement extends Components.IconPlay, HTMLStencilElement {
    }
    var HTMLIconPlayElement: {
        prototype: HTMLIconPlayElement;
        new (): HTMLIconPlayElement;
    };
    interface HTMLIconVolumeElement extends Components.IconVolume, HTMLStencilElement {
    }
    var HTMLIconVolumeElement: {
        prototype: HTMLIconVolumeElement;
        new (): HTMLIconVolumeElement;
    };
    interface HTMLElementTagNameMap {
        "dtpc-button": HTMLDtpcButtonElement;
        "dtpc-mute-button": HTMLDtpcMuteButtonElement;
        "dtpc-play-button": HTMLDtpcPlayButtonElement;
        "dtpc-player": HTMLDtpcPlayerElement;
        "dtpc-progress-bar": HTMLDtpcProgressBarElement;
        "dtpc-slider": HTMLDtpcSliderElement;
        "dtpc-time-current": HTMLDtpcTimeCurrentElement;
        "dtpc-time-display": HTMLDtpcTimeDisplayElement;
        "dtpc-time-duration": HTMLDtpcTimeDurationElement;
        "dtpc-volume-slider": HTMLDtpcVolumeSliderElement;
        "icon-pause": HTMLIconPauseElement;
        "icon-play": HTMLIconPlayElement;
        "icon-volume": HTMLIconVolumeElement;
    }
}
declare namespace LocalJSX {
    interface DtpcButton {
    }
    interface DtpcMuteButton {
        "onDtpc-control-init"?: (event: DtpcMuteButtonCustomEvent<any>) => void;
    }
    interface DtpcPlayButton {
        "onAudio-toggle-paused"?: (event: DtpcPlayButtonCustomEvent<any>) => void;
        "onDtpc-control-init"?: (event: DtpcPlayButtonCustomEvent<any>) => void;
    }
    interface DtpcPlayer {
        "duration"?: number;
        /**
          * Audio source URL.
         */
        "src"?: string;
    }
    interface DtpcProgressBar {
        "duration"?: number;
        "onDtpc-control-init"?: (event: DtpcProgressBarCustomEvent<any>) => void;
    }
    interface DtpcSlider {
        "defaultValue"?: number;
        "disabled"?: boolean;
        "max"?: number;
        "min"?: number;
        "onSlider-change"?: (event: DtpcSliderCustomEvent<number>) => void;
        "onSlider-input"?: (event: DtpcSliderCustomEvent<number>) => void;
        "orient"?: 'vertical' | 'horizontal';
        "step"?: number;
        "value"?: number;
    }
    interface DtpcTimeCurrent {
        "onDtpc-control-init"?: (event: DtpcTimeCurrentCustomEvent<any>) => void;
    }
    interface DtpcTimeDisplay {
        "duration"?: number;
    }
    interface DtpcTimeDuration {
        "duration"?: number;
        "onDtpc-control-init"?: (event: DtpcTimeDurationCustomEvent<any>) => void;
    }
    interface DtpcVolumeSlider {
        "onDtpc-control-init"?: (event: DtpcVolumeSliderCustomEvent<any>) => void;
        "orient"?: 'vertical' | 'horizontal';
        "volume"?: number;
    }
    interface IconPause {
        "alignmentBaseline"?: any;
        "baselineShift"?: any;
        "clipPath"?: any;
        "clipRule"?: any;
        "color"?: any;
        "colorInterpolation"?: any;
        "colorInterpolationFilters"?: any;
        "colorRendering"?: any;
        "cursor"?: any;
        "cx"?: any;
        "cy"?: any;
        "d"?: any;
        "direction"?: any;
        "display"?: any;
        "dominantBaseline"?: any;
        "fill"?: any;
        "fillOpacity"?: any;
        "fillRule"?: any;
        "filter"?: any;
        "floodColor"?: any;
        "floodOpacity"?: any;
        "font"?: any;
        "fontFamily"?: any;
        "fontKerning"?: any;
        "fontSize"?: any;
        "fontSizeAdjust"?: any;
        "fontStretch"?: any;
        "fontStyle"?: any;
        "fontVariant"?: any;
        "fontWeight"?: any;
        "height"?: any;
        "imageRendering"?: any;
        "isolation"?: any;
        "letterSpacing"?: any;
        "lightingColor"?: any;
        "marker"?: any;
        "markerEnd"?: any;
        "markerMid"?: any;
        "markerStart"?: any;
        "mask"?: any;
        "maskClip"?: any;
        "maskComposite"?: any;
        "maskImage"?: any;
        "maskMode"?: any;
        "maskOrigin"?: any;
        "maskPosition"?: any;
        "maskRepeat"?: any;
        "maskSize"?: any;
        "maskType"?: any;
        "opacity"?: any;
        "overflow"?: any;
        "pointerEvents"?: any;
        "r"?: any;
        "rx"?: any;
        "ry"?: any;
        "shapeRendering"?: any;
        "stopColor"?: any;
        "stopOpacity"?: any;
        "stroke"?: any;
        "strokeDasharray"?: any;
        "strokeDashoffset"?: any;
        "strokeLinecap"?: any;
        "strokeLinejoin"?: any;
        "strokeMiterlimit"?: any;
        "strokeOpacity"?: any;
        "strokeWidth"?: any;
        "textAnchor"?: any;
        "textDecoration"?: any;
        "textOrientation"?: any;
        "textRendering"?: any;
        "transform"?: any;
        "transformBox"?: any;
        "transformOrigin"?: any;
        "unicodeBidi"?: any;
        "visibility"?: any;
        "width"?: any;
        "wordSpacing"?: any;
        "writingMode"?: any;
        "x"?: any;
        "y"?: any;
    }
    interface IconPlay {
        "alignmentBaseline"?: any;
        "baselineShift"?: any;
        "clipPath"?: any;
        "clipRule"?: any;
        "color"?: any;
        "colorInterpolation"?: any;
        "colorInterpolationFilters"?: any;
        "colorRendering"?: any;
        "cursor"?: any;
        "cx"?: any;
        "cy"?: any;
        "d"?: any;
        "direction"?: any;
        "display"?: any;
        "dominantBaseline"?: any;
        "fill"?: any;
        "fillOpacity"?: any;
        "fillRule"?: any;
        "filter"?: any;
        "floodColor"?: any;
        "floodOpacity"?: any;
        "font"?: any;
        "fontFamily"?: any;
        "fontKerning"?: any;
        "fontSize"?: any;
        "fontSizeAdjust"?: any;
        "fontStretch"?: any;
        "fontStyle"?: any;
        "fontVariant"?: any;
        "fontWeight"?: any;
        "height"?: any;
        "imageRendering"?: any;
        "isolation"?: any;
        "letterSpacing"?: any;
        "lightingColor"?: any;
        "marker"?: any;
        "markerEnd"?: any;
        "markerMid"?: any;
        "markerStart"?: any;
        "mask"?: any;
        "maskClip"?: any;
        "maskComposite"?: any;
        "maskImage"?: any;
        "maskMode"?: any;
        "maskOrigin"?: any;
        "maskPosition"?: any;
        "maskRepeat"?: any;
        "maskSize"?: any;
        "maskType"?: any;
        "opacity"?: any;
        "overflow"?: any;
        "pointerEvents"?: any;
        "r"?: any;
        "rx"?: any;
        "ry"?: any;
        "shapeRendering"?: any;
        "stopColor"?: any;
        "stopOpacity"?: any;
        "stroke"?: any;
        "strokeDasharray"?: any;
        "strokeDashoffset"?: any;
        "strokeLinecap"?: any;
        "strokeLinejoin"?: any;
        "strokeMiterlimit"?: any;
        "strokeOpacity"?: any;
        "strokeWidth"?: any;
        "textAnchor"?: any;
        "textDecoration"?: any;
        "textOrientation"?: any;
        "textRendering"?: any;
        "transform"?: any;
        "transformBox"?: any;
        "transformOrigin"?: any;
        "unicodeBidi"?: any;
        "visibility"?: any;
        "width"?: any;
        "wordSpacing"?: any;
        "writingMode"?: any;
        "x"?: any;
        "y"?: any;
    }
    interface IconVolume {
        "alignmentBaseline"?: any;
        "baselineShift"?: any;
        "clipPath"?: any;
        "clipRule"?: any;
        "color"?: any;
        "colorInterpolation"?: any;
        "colorInterpolationFilters"?: any;
        "colorRendering"?: any;
        "cursor"?: any;
        "cx"?: any;
        "cy"?: any;
        "d"?: any;
        "direction"?: any;
        "display"?: any;
        "dominantBaseline"?: any;
        "fill"?: any;
        "fillOpacity"?: any;
        "fillRule"?: any;
        "filter"?: any;
        "floodColor"?: any;
        "floodOpacity"?: any;
        "font"?: any;
        "fontFamily"?: any;
        "fontKerning"?: any;
        "fontSize"?: any;
        "fontSizeAdjust"?: any;
        "fontStretch"?: any;
        "fontStyle"?: any;
        "fontVariant"?: any;
        "fontWeight"?: any;
        "height"?: any;
        "imageRendering"?: any;
        "isolation"?: any;
        "letterSpacing"?: any;
        "lightingColor"?: any;
        "marker"?: any;
        "markerEnd"?: any;
        "markerMid"?: any;
        "markerStart"?: any;
        "mask"?: any;
        "maskClip"?: any;
        "maskComposite"?: any;
        "maskImage"?: any;
        "maskMode"?: any;
        "maskOrigin"?: any;
        "maskPosition"?: any;
        "maskRepeat"?: any;
        "maskSize"?: any;
        "maskType"?: any;
        "muted"?: boolean;
        "opacity"?: any;
        "overflow"?: any;
        "pointerEvents"?: any;
        "r"?: any;
        "rx"?: any;
        "ry"?: any;
        "shapeRendering"?: any;
        "stopColor"?: any;
        "stopOpacity"?: any;
        "stroke"?: any;
        "strokeDasharray"?: any;
        "strokeDashoffset"?: any;
        "strokeLinecap"?: any;
        "strokeLinejoin"?: any;
        "strokeMiterlimit"?: any;
        "strokeOpacity"?: any;
        "strokeWidth"?: any;
        "textAnchor"?: any;
        "textDecoration"?: any;
        "textOrientation"?: any;
        "textRendering"?: any;
        "transform"?: any;
        "transformBox"?: any;
        "transformOrigin"?: any;
        "unicodeBidi"?: any;
        "visibility"?: any;
        "volume"?: number;
        "width"?: any;
        "wordSpacing"?: any;
        "writingMode"?: any;
        "x"?: any;
        "y"?: any;
    }
    interface IntrinsicElements {
        "dtpc-button": DtpcButton;
        "dtpc-mute-button": DtpcMuteButton;
        "dtpc-play-button": DtpcPlayButton;
        "dtpc-player": DtpcPlayer;
        "dtpc-progress-bar": DtpcProgressBar;
        "dtpc-slider": DtpcSlider;
        "dtpc-time-current": DtpcTimeCurrent;
        "dtpc-time-display": DtpcTimeDisplay;
        "dtpc-time-duration": DtpcTimeDuration;
        "dtpc-volume-slider": DtpcVolumeSlider;
        "icon-pause": IconPause;
        "icon-play": IconPlay;
        "icon-volume": IconVolume;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dtpc-button": LocalJSX.DtpcButton & JSXBase.HTMLAttributes<HTMLDtpcButtonElement>;
            "dtpc-mute-button": LocalJSX.DtpcMuteButton & JSXBase.HTMLAttributes<HTMLDtpcMuteButtonElement>;
            "dtpc-play-button": LocalJSX.DtpcPlayButton & JSXBase.HTMLAttributes<HTMLDtpcPlayButtonElement>;
            "dtpc-player": LocalJSX.DtpcPlayer & JSXBase.HTMLAttributes<HTMLDtpcPlayerElement>;
            "dtpc-progress-bar": LocalJSX.DtpcProgressBar & JSXBase.HTMLAttributes<HTMLDtpcProgressBarElement>;
            "dtpc-slider": LocalJSX.DtpcSlider & JSXBase.HTMLAttributes<HTMLDtpcSliderElement>;
            "dtpc-time-current": LocalJSX.DtpcTimeCurrent & JSXBase.HTMLAttributes<HTMLDtpcTimeCurrentElement>;
            "dtpc-time-display": LocalJSX.DtpcTimeDisplay & JSXBase.HTMLAttributes<HTMLDtpcTimeDisplayElement>;
            "dtpc-time-duration": LocalJSX.DtpcTimeDuration & JSXBase.HTMLAttributes<HTMLDtpcTimeDurationElement>;
            "dtpc-volume-slider": LocalJSX.DtpcVolumeSlider & JSXBase.HTMLAttributes<HTMLDtpcVolumeSliderElement>;
            "icon-pause": LocalJSX.IconPause & JSXBase.HTMLAttributes<HTMLIconPauseElement>;
            "icon-play": LocalJSX.IconPlay & JSXBase.HTMLAttributes<HTMLIconPlayElement>;
            "icon-volume": LocalJSX.IconVolume & JSXBase.HTMLAttributes<HTMLIconVolumeElement>;
        }
    }
}
